### ISSUE TITLE
some links 

### ISSUE THREAD

**Issue by ekswathi** [KoreTeknology/Blender-3x-Audio-Research#1]
The links below are related to midi with nodes.  I hope it helps

https://www.bespokesynth.com/
https://github.com/nomelif/Audionodes

**Comment by KoreTeknology** [comment]
@ekswathi I am also looking at the midi implementation, i am using RTmidi in addons, not sure how this can be by default...

**Comment by ekswathi** [comment]
Really sorry bro.  I don't have any connection with the Bespoke synth except i am a regular user.
And same with Audionodes addon.  Best part with Audionodes addon is it is working with Blender 3.1, and 3.2.  Did you tried it?
When I see your research which I feel really interesting and I thought these will help.  
I really hope one day there will be VST support for blender VSE
Thank you
One more link: (it is not related to midi but audio in vse)
https://github.com/technisculpt/blender-text-to-speech-gtts
